In [73]:
!pip install numpy

In [74]:
import numpy as np

In [75]:
a = np.array([5,4,3,2,1,"a"])

In [76]:
print(a)

['5' '4' '3' '2' '1' 'a']


In [77]:
a

array(['5', '4', '3', '2', '1', 'a'], dtype='<U21')

In [78]:
a = np.array(55)
b = np.array([22,33,44,55])
c = np.array([[1.3,2.34,3.78],[4.20,5.3,6.12]])
d = np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])


In [79]:
print("0D:",a)
print("1D:",b)
print("2D:",c)
print("3D:",d)

0D: 55
1D: [22 33 44 55]
2D: [[1.3  2.34 3.78]
 [4.2  5.3  6.12]]
3D: [[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]


In [80]:
print(f"Dimension of a is  {a.ndim}")
print(f"Dimension of b is  {b.ndim}")
print(f"Dimension of c is  {c.ndim}")
print(f"Dimension of d is  {d.ndim}")

Dimension of a is  0
Dimension of b is  1
Dimension of c is  2
Dimension of d is  3


In [81]:
print(a.dtype)
print(c.dtype)
print(type(a))
print(type(c))


int64
float64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [82]:
print(a)
print("Shape of a:",a.shape)
print(b)
print("Shape of b:",b.shape)
print(c)
print("Shape of c:",c.shape)
print(d)
print("Shape of d:",d.shape)

55
Shape of a: ()
[22 33 44 55]
Shape of b: (4,)
[[1.3  2.34 3.78]
 [4.2  5.3  6.12]]
Shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
Shape of d: (2, 2, 3)


In [20]:
print(b)
print(len(b))

[22 33 44 55]
4


In [21]:
num = np.arange(1,11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
num1 = np.arange(1,21,2)
num1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.arange(1,21,3)


array([ 1,  4,  7, 10, 13, 16, 19])

In [24]:
arr = np.eye(5)
arr



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr1 = np.eye(5,dtype = "int")
arr1


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
arr2 = np.zeros((5,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr2 = np.zeros((4,4),dtype = "int")
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
arr3 = np.ones((5,7))
arr3

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr3 = np.ones((3,6),dtype = "int")
arr3

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [30]:
arr4 = np.full((4,5),5,dtype = "int")
arr4

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [31]:
arr5 = np.full((5,7),9,dtype = "int")
arr5

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [32]:
elements = [8,7,6,5,4]
np.diag(elements)

array([[8, 0, 0, 0, 0],
       [0, 7, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 4]])

In [33]:
np.diag([11,22,33,44,55])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [34]:
arr = np.arange(1,17)
print(arr)
print(arr.shape)
print(arr.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [35]:
arr.reshape((2,8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [36]:
arr.reshape((8,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [37]:
arr.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr.reshape((1,16))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [39]:
arr.reshape(16,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [40]:
arr.reshape((2,2,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [41]:
arr.reshape((4,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [42]:
arr.reshape((4,4,1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]]])

In [43]:
arr.reshape((4,1,4))

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]],

       [[13, 14, 15, 16]]])

In [44]:
arr.reshape(1,4,4)



array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [45]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
y=x.ravel()
print("y:",y)
print("x:",x)

y: [1 2 3 4 5 6]
x: [[1 2 3]
 [4 5 6]]


In [47]:
print(x)

[[1 2 3]
 [4 5 6]]


In [48]:
m = np.arange(2,11,2)
print(m)
print(m[3])
print(m[-1])
print(m[::-1])
print(m[2:4])
print(m[:3])
print(m[2:])

[ 2  4  6  8 10]
8
10
[10  8  6  4  2]
[6 8]
[2 4 6]
[ 6  8 10]


In [111]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[1,2])
print(b[0,1])
print(b[2,0])
print(b[1,2])
print(b[2,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
2
7
6
8


In [50]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)
print(c[0][1][1])
print(c[1][0][2])
print(c[0][1][1])
print(c[1][0][0])
print()

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
5
9
5
7



In [51]:
print(m)
print(m[::2])

[ 2  4  6  8 10]
[ 2  6 10]


In [52]:
print(b)
#print(b[1:,2])
#print(b[1:3,2])
#print(b[0:2,0])
#print(b[0:2,2])
#print(b[0,:])
#print(b[2,0:2])
print(b[0:2,1:3])
print(b[1:,1:])
print(b[:,:2])
print(b[0::2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[5 6]
 [8 9]]
[[1 2]
 [4 5]
 [7 8]]
[3 9]


In [53]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [54]:
#3D array slicing
print(c[0,1,0:2])
print(c[1,:,0:2])
print(c[0:,1,0:2])
print(c[1,0:,1:])
print(c[[0,1],[1,0],:2])
print(c[[0,1],[1,0],1:])

[4 5]
[[ 7  8]
 [10 11]]
[[ 4  5]
 [10 11]]
[[ 8  9]
 [11 12]]
[[4 5]
 [7 8]]
[[5 6]
 [8 9]]


In [55]:
#view or assign
z = np.arange(16)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
z1 = z # view or assign
print(z)
print(z1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [57]:
z1[1] = 25
print(z)
print(z1)
print("ID of z :",id(z))
print("ID of z1:",id(z1))
print("Memory location :",np.shares_memory(z,z1))




[ 0 25  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0 25  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
ID of z : 134340472809072
ID of z1: 134340472809072
Memory location : True


In [58]:
z2 = z1.view()
print(z2)
print("Memory location :",np.shares_memory(z1,z2))



[ 0 25  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Memory location : True


In [59]:
z2 [5] = 55
print(z2)
print(z1)

[ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]
[ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]


In [60]:
num = np.copy(z1)
print(num)

[ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]


In [61]:
num[-1] = 111
print("num elements:",num)
print("z1 elements:",z1)
print("ID of num :",id(num))
print("ID of z1:",id(z1))
print("Memory location :",np.shares_memory(num,z1))



num elements: [  0  25   2   3   4  55   6   7   8   9  10  11  12  13  14 111]
z1 elements: [ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]
ID of num : 134340472927024
ID of z1: 134340472809072
Memory location : False


In [112]:
# operations on array
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
print( b > 5)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [64]:
print(b <= 3)

[[ True  True  True]
 [False False False]
 [False False False]]


In [65]:
b[b > 5]

array([6, 7, 8, 9])

In [66]:
b[(b > 3) & (b < 8)]

array([4, 5, 6, 7])

In [67]:
print(num)
print(z1)

[  0  25   2   3   4  55   6   7   8   9  10  11  12  13  14 111]
[ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]


In [68]:
num == z1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False])

In [69]:
#transpose()
print(b)
print("\nTranspose of b:",b.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of b: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [70]:
#vstack and hstack
print(z)
print(z1)

[ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]
[ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]


In [71]:
np.vstack((z,z1))

array([[ 0, 25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0, 25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [84]:
np.vstack((num,z2))

array([[  0,  25,   2,   3,   4,  55,   6,   7,   8,   9,  10,  11,  12,
         13,  14, 111],
       [  0,  25,   2,   3,   4,  55,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15]])

In [86]:
np.hstack((z,z1))

array([ 0, 25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  0,
       25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
np.hstack((z1,z2))

array([ 0, 25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  0,
       25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
#insert function
print("z1:",z1)
print("num:",num)
np.insert(z1,5,num)

z1: [ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]
num: [  0  25   2   3   4  55   6   7   8   9  10  11  12  13  14 111]


array([  0,  25,   2,   3,   4,   0,  25,   2,   3,   4,  55,   6,   7,
         8,   9,  10,  11,  12,  13,  14, 111,  55,   6,   7,   8,   9,
        10,  11,  12,  13,  14,  15])

In [101]:
print("z",z)
print("arr",arr)
print("\n")
np.insert(arr,2,z)

z [ 0 25  2  3  4 55  6  7  8  9 10 11 12 13 14 15]
arr [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]




array([ 1,  2,  0, 25,  2,  3,  4, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [107]:
#delete()
print(arr)
print("\n")
np.delete(arr,9)
np.delete(arr,0)
np.delete(arr,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]




array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [116]:
print(b)
np.sin(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [117]:
np.tan(b)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [118]:
print(np.exp(b))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [119]:
print(np.exp(arr))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06]


In [134]:
print(b)
print("sum of b elements:",np.sum(b))
print("maximum element:",np.max(b))
print("Minimum of b:",np.min(b))
print("Column sum :",np.sum(b,axis=0))
print("Row sum:",np.sum(b,axis=1))
print("Mean of b elements:",np.mean(b))
print("Median of b elements:",np.median(b))
print("Standard deviation :",np.std(b))
#print(np.where(b>7))




[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of b elements: 45
maximum element: 9
Minimum of b: 1
Column sum : [12 15 18]
Row sum: [ 6 15 24]
Mean of b elements: 5.0
Median of b elements: 5.0
Standard deviation : 2.581988897471611
(array([2, 2]), array([1, 2]))


In [135]:
print(dir(tuple))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [136]:
print(dir(dict))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [137]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [138]:
flatten_b = b.flatten()
print(flatten_b)

[1 2 3 4 5 6 7 8 9]


In [148]:
flatten_b[2] = 55
print(flatten_b)
print(b)
print(np.shares_memory(flatten_b,b))

[ 1  2 55  4  5  6  7  8  9]
[[ 1  2 55]
 [ 4  5  6]
 [ 7  8  9]]
False


In [142]:
ravel_b = b.ravel()
print(ravel_b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [146]:
ravel_b[2] = 55
print(ravel_b)
print(b)
print(np.shares_memory(ravel_b,b))


[ 1  2 55  4  5  6  7  8  9]
[[ 1  2 55]
 [ 4  5  6]
 [ 7  8  9]]
True
